/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crowdfundingSol from "./Crowdfunding.sol";
export type { crowdfundingSol };
export type { AreaCalculation } from "./AreaCalculation";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { AreaCalculation__factory } from "./factories/AreaCalculation__factory";
export type { CrowdFunding } from "./Crowdfunding.sol/CrowdFunding";
export { CrowdFunding__factory } from "./factories/Crowdfunding.sol/CrowdFunding__factory";
export { Lock__factory } from "./factories/Lock__factory";
